### PR TITLE
rule abapdoc, add ignoreTestClasses option

### PR DESCRIPTION
**Pull request by jan-jezek**

### CODE REVIEW

**Comment by jan-jezek** [comment]
I am debating whether the option should be off/on by default (currently off) and whether this should be an option at all.
I think that forcing abapdoc on global testclasses can be seen as a bug and not a feature.

**Comment by larshp** [comment]
yea, set it to default ignore the testclasses, having the option makes it visible, which is good, somebody might need it for something, sometime :)

**Comment by larshp** [comment]
thanks 👍

**Comment by larshp** [comment]
published as 2.105.6

**Pull request merged**
