### PR TITLE
ci docs

### PR DESCRIPTION
**Pull request by sbcgua**
Some useful examples. All repo examples are actualized.

To add in future:
- dockerised check
- bitbucket ?
- abaplint-backend-for-sci

### CODE REVIEW

**Comment by larshp** [comment]
think its a good idea to collect these in the main repo

I'm not sure if the "node slim" docker images actually work, but for gitlab, see link in https://github.com/abaplint/abaplint/issues/823

**Comment by larshp** [comment]
the slim docker images does not include `git` command line, which is used in abaplint to retrieve dependencies

**Comment by sbcgua** [comment]
all the above works. But it's a good point about git. I'll fix to regular image

**Comment by larshp** [comment]
ref https://github.com/abaplint/abaplint/blob/master/packages/cli/src/cli.ts#L90

**Comment by sbcgua** [comment]
Done. Both in example and in the sample repo.

Yeah, I know about git, tnx. I explicitly add it to alpine image in docker. But I forgot that it was not present in slim (don't use it a lot)

**Comment by larshp** [comment]
👍 

should also sometime clean up the readme, too much stuff in it, link to these docs instead

**Comment by sbcgua** [comment]
yeah ... especially official `@abaplint/*` npm packages without readme look strange ;)

**Pull request merged**
