### PR TITLE
Fix "Transformation 'id' not found"

### PR DESCRIPTION
**Pull request by mbtools**

### CODE REVIEW

**Comment by larshp** [comment]
ID is at https://github.com/abaplint/deps/blob/master/src/id.xslt.xml, so it should not be needed to hardcode it?

**Comment by mbtools** [comment]
I thought when called from SCI, it ignores abaplint/deps. No?

**Comment by larshp** [comment]
when called from SCI, it should find the ID dependency and send to the javascript server

**Comment by mbtools** [comment]
Ok. Will have to add it to backend deps for SCI.

**Pull request closed without merging**
