### PR TITLE
Improve debug descriptions

### LINKED ISSUE #3136: Improve debug descriptions
We can easily improve the debugging experience adding `Symbol.for("debug.description")` methods, going i.e. from:
image
to 
image

### PR DESCRIPTION
**Pull request by marcellourbani**
Fixes #3136

Just scratching my own itch, found it pretty tough to debug without this.
Only did some low hanging/highly annoying bits like SpaghettiScopeNode

### CODE REVIEW

**Comment by larshp** [comment]
this seems magic, any documentation references,? is this a vscode feature or more?

**Comment by marcellourbani** [comment]
I spent way more time looking for it than implementing (I knew existed because saw something similar some time ago)
The closest I found to documentation is [this changelog](https://github.com/microsoft/vscode-js-debug/blob/main/CHANGELOG.md) and the [issue linked in it](https://github.com/microsoft/vscode/issues/102181)

Deserves more imho, but here you go

**Comment by marcellourbani** [comment]
There's another variant (I believe also supported by vscode but more general) which is better documented as part of [standard node](https://nodejs.org/api/util.html#utilinspectcustom)
Didn't try it yet

Found both [here](https://github.com/microsoft/vscode-js-debug/blob/main/src/adapter/templates/getStringyProps.ts)

**Comment by marcellourbani** [comment]
Another step down the rabbit hole:

These are vscode and node specific, but [chrome](https://docs.google.com/document/d/1FTascZXT9cxfetuPRT2eXPQKXui4nWFivUnS_335T3U/preview) and [firefox](https://fxdx.dev/firefox-devtools-custom-object-formatters/)
Found them [here](https://devtoolstips.org/tips/en/custom-object-formatters/)
edge should work too

**Comment by larshp** [comment]
thanks

**Pull request merged**
