### PR TITLE
Added docstrings to rule configs

### PR DESCRIPTION
**Pull request by FreHu**
- still missing a few rules
- maybe make the error descriptions a bit more friendly as well

### CODE REVIEW

**Comment by larshp** [comment]
cool, lets just merge it?

**Comment by FreHu** [comment]
Still unsure about a few:

- check_variables enables some sort of variable analysis?
- I don't know anything about rfc error handling
- ambiguous_statement
- empty_statement

**Comment by larshp** [comment]
check_variables: checks that the variables referenced are defined somewhere, this is much work in progress
rfc error handling: the exceptions from example https://help.sap.com/doc/abapdocu_752_index_htm/7.52/en-us/abenrfc_exceptions_abexa.htm must be defined in the code
ambigious statement: in some cases the parser cannot tell if it is a database or internal table it is working on, this check forces the developer to make it explicit
empty statement: gives error for abap code `.`

**Comment by FreHu** [comment]
Feel free to merge. I won't change the `get_description` methods in this PR as they're not used if they need parameters anyway.

**Comment by larshp** [comment]
hmm, the schema did not update, and I can reproduce locally

did you run it locally?

**Comment by larshp** [comment]
fixed, https://github.com/abaplint/schema.abaplint.org/commit/4497aada80d7e4c89e50c1f31ec18029a5f01d52

**Pull request merged**
