### PR TITLE
Pushbutton to accept text element or variable

### PR DESCRIPTION
**Pull request by mbtools**
Works like SELECTION-SCREEN COMMENT
Closes https://github.com/abaplint/abaplint/issues/885

### CODE REVIEW

**Comment by larshp** [comment]
thanks, also please add unit tests to https://github.com/abaplint/abaplint/blob/master/packages/core/test/abap/statements/selectionscreen.ts

**Comment by mbtools** [comment]
There are plenty of PUSHBUTTTON tests. A unit test for this case would require several lines since the issue occurs only when some other statement tries to update the variable used in PUSHBUTTON. Is that possible for a test?

**Comment by larshp** [comment]
its a bit more work, take a look at https://github.com/abaplint/abaplint/blob/master/packages/core/test/rules/check_text_elements.ts it contains the unit tests for the rule this PR does a fix for

**Comment by larshp** [comment]
the code `SELECTION-SCREEN PUSHBUTTON 60(30) text-103 USER-COMMAND btn.` we expect to give one error regarding the missing text element

**Comment by larshp** [comment]
looks good to me 👍 thanks

**Pull request merged**
