### PR TITLE
Add regression test to all pull requests

### PR DESCRIPTION
**Pull request by g-back**
See #1236 , regression test was not triggered

Also fix typos introduced in aforementioned PR

### CODE REVIEW

**Comment by g-back** [comment]
NVM, didn't see comment in #1109

**Comment by larshp** [comment]
its a "feature" in GitHub, pull requests from forks doesn't have permissions to do nice things

**Comment by larshp** [comment]
but also feel free to create branches in this repository, just prefix them with your name "gback/something"

**Comment by g-back** [comment]
Looks like you can use `pull_request_target`, will look further into it

**Comment by g-back** [comment]
Looks like the `gh-find-current-pr` app does not work on pull requests so it does not find the PR number currently

**Comment by larshp** [comment]
yea, the permissions stuff is a mess on github currently for PRs from forks

**Pull request closed without merging**
