### PR TITLE
auto tag workflow

### PR DESCRIPTION
**Pull request by sbcgua**
potentially may need the first tag to be created manually ... but maybe will work

triggered only on `package.json` change

### CODE REVIEW

**Comment by larshp** [comment]
thanks, lets try it

**Comment by sbcgua** [comment]
will deploy a docker workflow in a while ... ;)

**Comment by larshp** [comment]
okay :)

**Comment by larshp** [comment]
I publish new versions all the time, so lets wait until next publish to see if it works

**Comment by sbcgua** [comment]
there is a mistake ... I'll create a new PR ... for got to change the repo name

**Comment by sbcgua** [comment]
`if: github.ref == 'refs/heads/master' && github.repository == 'abaplint/abaplint'`

**Comment by larshp** [comment]
broken, https://github.com/abaplint/abaplint/commit/2ebf94264e9be525205aa9114fedf848936b3569/checks?check_suite_id=379540751

**Comment by sbcgua** [comment]
I think this is because of missing tags. Can you a tag to a **previous** version manually ? and then rerun the job (the same one, it should see the same commit).

**Comment by larshp** [comment]
what is the format, will "2.20.4" work?

**Comment by sbcgua** [comment]
v2.20.4

**Comment by sbcgua** [comment]
the script expects "v" at the beginning

**Comment by sbcgua** [comment]
But try to tag v2.20.3 and then rerun the job - the v2.20.4 should be added automatically

**Comment by larshp** [comment]
success, https://github.com/abaplint/abaplint/runs/370949414

**Comment by sbcgua** [comment]
🎉 great ! :) Nice that it works.
The next step is auto docker image then. Could you pls write your opinion on my last post at #533 pls?

**Pull request merged**
