### PR TITLE
Enhance in_statement_indentation

### PR DESCRIPTION
**Pull request by mbtools**
- Add option to specify additional indent for block statements (set to 0 if you don't want this)
- Extend description and examples
- Add CASE to block statements (probably rare that it spans multiple lines)

### CODE REVIEW

**Comment by mbtools** [comment]
I can't figure out why test new test is failing 😢

**Comment by larshp** [comment]
see line 77 in the rule logic

**Comment by mbtools** [comment]
yes, the regular indent is 2. the test sets `blockStatements` to 0 so the expected indent for `if` should remain at 2. the test which fails has indent of 2 so there should be no issue raised.

**Comment by larshp** [comment]
yea, hmm

**Comment by larshp** [comment]
fixed :)

**Comment by larshp** [comment]
yea, guess its also buggy

anyhow, merging this one, thanks 👍 I'll open a different PR sometime to have the regression test run

**Comment by larshp** [comment]
published in 2.76.12

**Pull request merged**
