### PR TITLE
avoid_use - add quickfix for describe lines

### PR DESCRIPTION
**Pull request by jan-jezek**
`DESCRIBE TABLE foo LINES bar.`
will be changed to
`bar = lines( foo ).`

### CODE REVIEW

**Comment by jan-jezek** [comment]
For some reason the newest commit was not shown in ##1685 properly.

**Comment by larshp** [comment]
guess its also possible to have code like `DESCRIBE TABLE moo( ) LINES bar."

you can do stuff like `statementNode.findDirectExpression(Expressions.Source)` to find the right children in the AST, https://syntax.abaplint.org/?filter=describe#/statement/Describe

**Comment by jan-jezek** [comment]
> guess its also possible to have code like `DESCRIBE TABLE moo( ) LINES bar."
> 
> you can do stuff like `statementNode.findDirectExpression(Expressions.Source)` to find the right children in the AST, https://syntax.abaplint.org/?filter=describe#/statement/Describe

Cool, but I don't get what the problem would be in this situation...
`bar = lines( moo( ) ).`
should be correct (and playground returns that) if
`DESCRIBE TABLE moo( ) LINES bar.`
is correct.

**Comment by larshp** [comment]
yea, I think the current implementation works 👍

**Comment by FreHu** [comment]
`DESCRIBE TABLE moo( ) LINES bar.` is not valid, but accepted by abaplint

according to keyword documentation only `itab` is supported in this position

**Comment by larshp** [comment]
@FreHu thanks, can you help opening it as a separate issue?

**Comment by jan-jezek** [comment]
I think the work on this is done. Can be merged from my side.

**Comment by larshp** [comment]
@jan-jezek yea, I'll merge it tomorrow

**Pull request merged**
