### PR TITLE
Add POPUP_TO_CONFIRM_STEP to function_module_recommendations

### PR DESCRIPTION
**Pull request by jan-jezek**
POPUP_TO_CONFIRM_STEP is obsolete since long ago, use POPUP_TO_CONFIRM instead

### CODE REVIEW

**Comment by larshp** [comment]
thanks, just change the one line instead of changing overall formatting?

**Comment by jan-jezek** [comment]
Sorry about that :)

**Comment by larshp** [comment]
thanks, it will be part of next release

**Comment by larshp** [comment]
published as 2.95.50

**Pull request merged**
