### PR TITLE
keyword_case: add option, list of keywords to ignore

### LINKED ISSUE #745: keyword_case rule: add option to ignore list of words
keyword_case rule: add option to ignore list of words

### PR DESCRIPTION
**Pull request by g-back**
closes #745
Add option: list of keywords to ignore. Also affects pretty printer

### CODE REVIEW

**Comment by larshp** [comment]
this should be a user setting, allowing users to choose which style to enforce/or not to enforce

**Comment by g-back** [comment]
True, but in this specific case it's an actual bug, isn't it? At least in 7.40 'TEXT' is not regarded as a keyword in the context of the default pretty printer, at least in terms of upper-/lowercase.

**Comment by larshp** [comment]
yea, but if a customer have all SAP systems on the latest greatest HANA S/4, I personally would like to enforce this rule, have TEXT only be upper case

**Comment by g-back** [comment]
How about this:
 - for "TEXT" in selection screen specifically I add a version check, ignore word if release version below 750
 - addtionally add option to ignore specific words

**Comment by larshp** [comment]
I think it must be a user setting, could also be someone working on a 740 system, but wanting to pretty print according to 750 logic

**Comment by larshp** [comment]
thanks, looks good 👍

**Pull request merged**
