### PR TITLE
Pretty Printer: Trailing whitespace

### LINKED ISSUE #564: pretty printer adds newlines
place cursor like this, and trigger pretty print multiple times, adds newlines

image

### PR DESCRIPTION
**Pull request by g-back**
- Remove trailing (and leading) whitespace with a simple trim (tries to resolve #564)
- The effect in the playground is that no new lines are added - but the trailing whitespace is NOT removed. The cause could lie within mono/language server itself?

pretty_print

### CODE REVIEW

**Comment by g-back** [comment]
Interestingly, when I change the following line:
https://github.com/abaplint/abaplint/blob/24a20fe8ff9f8e0a39260f2c52bcedfc40518208/src/lsp/index.ts#L58
to

```typescript
range: LServer.Range.create(0, 0, Number.MAX_VALUE, 0),
```
it works:

pretty_print_2

**Comment by larshp** [comment]
hmm, yea, looks like there is a twist there, not exactly sure what the range in TextEdit means

**Comment by g-back** [comment]
Should I just add the change for the time being?

**Comment by larshp** [comment]
hmm, yea, makes sense

**Pull request merged**
