### PR TITLE
playground - travis rm -Rf old deploy before copying new

### PR DESCRIPTION
**Pull request by sbcgua**
remove old pg files before new deploy
P.S. `.git` folder stays untouched

### CODE REVIEW

**Comment by larshp** [comment]
the CNAME file is required for the domain to work,
image

**Comment by larshp** [comment]
easy solution is just to clean up the repo manually

**Comment by sbcgua** [comment]
ah yes, missed that ... hmm ... how to make it better ... some kind of gitkeep ... will think about it but not today already :)

**Comment by larshp** [comment]
just clean it up manually, its not something that changes much once the overall playground setup is done

**Pull request closed without merging**
