### PR TITLE
class_attribute_names: add constants, add ignoreLocal

### PR DESCRIPTION
**Pull request by g-back**
part of #716 

add naming for constants
add option to ignore local classes

~~currently errors during schema generation ->caused by faulty import statement~~

### CODE REVIEW

**Comment by larshp** [comment]
have to consider what the default setting should be, in some other rule the "C_" is changing parameters

**Comment by g-back** [comment]
I suppose `CO_` is the only viable alternative? Abapgit uses `GC_` but that doesn't seem to make much sense

**Comment by larshp** [comment]
suggest easy solution is: allow everything in the default, let the users configure

**Comment by larshp** [comment]
thanks 👍

**Pull request merged**
