### PR TITLE
extract FAMIX model for moose

### PR DESCRIPTION
**Pull request by pascalerni**
With this pull request, abaplint can extract model information (MSE file) for software analyses with the moose platform (http://moosetechnology.org).

- the most new code are in /src /extras/moose
- in /src/extras/moose/model/ is a typescript implementation of the FAMIX 3.0 Meta Model.
- the model_*.ts Classes parse the nodes and transform the relevant information into a FAMIX model

thx for review this pull request.

### CODE REVIEW

**Comment by larshp** [comment]
Few questions,

Many of the files says they are automatically generated, I'm not a fan of putting generated code into version management.
Have you considered putting the model implementation in a separate npm package? I guess it does not change much over time?
Have you considered putting the extractor into a separate npm package? And call the abaplint functionality?
Quickly looking through the code it looks like there are no tests?

**Comment by pascalerni** [comment]
> Many of the files says they are automatically generated, I'm not a fan of putting generated code into version management.
> Have you considered putting the model implementation in a separate npm package? I guess it does not change much over time?

- You're right. I will make a npm package for the FAMIX model. The classes are generated by a generator written in java. I will set up a travis build for this. That's a good idea.

> Have you considered putting the extractor into a separate npm package? And call the abaplint functionality?
- I tried this at the beginning without success. But at this time my abaplint knowhow was still very limited. Do you have an example on how to use abaplint as library?

**Comment by larshp** [comment]
I'll create a small example, give me a few hours, also feel free to join slack, https://abapgit-slackinviter.herokuapp.com/ there is a #abaplint channel

**Comment by larshp** [comment]
see https://github.com/abaplint/abaplint-lib-example 

perhaps more stuff must be added in https://github.com/abaplint/abaplint/blob/master/src/index.ts

**Comment by pascalerni** [comment]
Thank you for the example. A first attempt was successful. I have now created the project https://github.com/pascalerni/abap2famix

**Comment by larshp** [comment]
I do break and change a lot of stuff in abaplint, you can fix the version of abaplint to a specific one in abaplint.

Alternatively setup CI and Greenkeeper

**Pull request closed without merging**
