### PR TITLE
New rule - Constant classes

### PR DESCRIPTION
**Pull request by FreHu**
#2125

### CODE REVIEW

**Comment by larshp** [comment]
👍

**Comment by FreHu** [comment]
@larshp here i have a problem with the lines 
```ts
const classContents = classWithConstants?.getFiles()[0] as ABAPFile;
const info = classContents.getInfo();
```
as the tests use MemoryFile which does not have this method i'm not sure if i'm accessing or mocking the file incorrectly

**Comment by larshp** [comment]
fixed in https://github.com/FreHu/abaplint/commit/329cc1237bc09ca4586edd9221cbc76e95c5d8c4

cast the getObject,
`this.reg.getObject("CLAS", configEntry?.class) as Class | undefined;`
then its possible to call
```
classWithConstants.getMainABAPFile();
classWithConstants.getClassDefinition();
```

**Comment by larshp** [comment]
published in 2.79.0

**Pull request merged**
