### PR TITLE
Make language version optional in config, up default to 755

### LINKED ISSUE #1562: Add "latest" version option
This would always parse using the latest available version.

### PR DESCRIPTION
**Pull request by FreHu**
Resolves #1562 .

There are some whitespace inconsistencies when I run the schema script. I will undo them, but I'd like to know the cause - I did a fresh clone just to be sure and they still appear.

### CODE REVIEW

**Comment by larshp** [comment]
also see https://github.com/abaplint/abaplint/issues/1139

**Comment by larshp** [comment]
I'd like the script to align the whitespace but 🤷‍♂️

**Comment by FreHu** [comment]
It's one of my predictions that the world will end when an important enough newline is lost somewhere and everything will break. But probably not here.

**Comment by larshp** [comment]
thanks 👍

**Comment by larshp** [comment]
2.63.2 published

**Pull request merged**
